#!/usr/bin/env bash
# Bash script that will display information about subdomains.
get_subdomain_info () {
  local subdomain="$1.$2"
  local output
  output=$(dig +short "$subdomain")
  
  if [ -z "$output" ]; then
    echo "The subdomain $1 does not exist."
  else
    echo "The subdomain $1 is A record and points to $output"
  fi
}

if [ -z "$1" ]; then
  echo "The domain argument is mandatory."
else
  if [ -z "$2" ]; then
    for sub in www lb-01 web-01 web-02; do
      get_subdomain_info "$sub" "$1"
    done
  else
    get_subdomain_info "$2" "$1"
  fi
fi
