#!/usr/bin/env bash
# Bash script that tranfers a file from client to a server

#!/bin/bash

# Check if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the parameters to variables for better readability
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Use scp to transfer the file
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/
