#!/usr/bin/env bash
# Install and configure Nginx web server

# Update the package list to get the latest package information
# Install Nginx using the package manager
# Allow incoming HTTP traffic through the firewall
# Create a default HTML file with "Hello World!" content
# Start the Nginx service to make it active

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
