#!/usr/bin/env bash
# Bash script to configure Nginx for URL redirection

# Define strings for search and replace in Nginx configuration
oldstr="server_name _;"
newstr="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

# Update the package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a simple HTML file in the default web root
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Modify Nginx configuration to add URL redirection
sudo sed -i -e "s|$oldstr|$newstr|" /etc/nginx/sites-enabled/default

# Start the Nginx service to apply the changes
sudo service nginx start
