#!/usr/bin/env bash
# Bash script to configure Nginx for custom 404 page

# Update packages and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a new Nginx configuration file
sudo tee /etc/nginx/sites-available/my_custom_site <<EOF
server {
    listen 80 default_server;
    server_name _;

    # Redirect /redirect_me to YouTube
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Custom 404 page
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }

    # Your other location blocks go here...

    # Additional configuration as needed...
}
EOF

# Enable the new site by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/my_custom_site /etc/nginx/sites-enabled/

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart

