#!/usr/bin/env bash
# Bash script to configure Nginx for custom 404 page and custom HTTP header

# Update packages and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Configure redirection from /redirect_me to YouTube
oldstr="server_name _;"
newstr="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i -e "s|$oldstr|$newstr|" /etc/nginx/sites-available/default

# Configure custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
oldstr="error_page 404 /404.html;"
newstr="error_page 404 /custom_404.html;"
sudo sed -i -e "s|$oldstr|$newstr|" /etc/nginx/sites-available/default

# Configure custom HTTP header
echo -e "\tadd_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/sites-available/default

# Restart nginx service to apply changes
sudo service nginx restart
