#!/usr/bin/env bash
#Bash script that display listening sockets 
#This  command lists all listening sockets
#And shows the PID  and name of the program to which each socket belongs
netstat -l --program
