#!/usr/bin/env bash
# Nginx Port 80 Configuration

#!/usr/bin/env bash
# Nginx Port 80 Configuration

# Remove the default Nginx configuration if it exists
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the configuration changes
service nginx restart
