#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd
#Display username
#Display user id
#Display Home directory path for the user

while IFS=: read -r username _ uid _ _ home _; do
      echo "username: $username"
      echo "user id: $uid"
      echo "Home directory path for the user: $home"
      echo
done < /etc/passwd
