#!/usr/bin/env bash
#Create the file containing its PID.
#Display "To infinity and beyond" indefinitely
#Display "I hate the kill command" when receiving a SIGTERM signal
#Display "Y U no love me?!" when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ > /var/run/myscript.pid

trap "echo I hate the kill command; sudo rm /var/run/myscript.pid" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm /var/run/myscript.pid" SIGQUIT

while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
