#!/usr/bin/env bash
#Bah script that displays the content of the file /etc/passwd using a while loop.
#Displays username 
#Disaplays user id
#Displays Home directory path  for the user.

while IFS=: read -r username _ uid _ _ home _; do
      echo "$username:$uid:$home"
done < /etc/passwd
