#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 using while loop and:
#Display 4 and then bad luck from china for the 4th loop iteration
#Display 9 and then bad luck from Japan for the 9th iteratiob
#Display 17 and the bad luck form Italy for the 17th loop iteration

i=1
while [ $i -le 20 ]
do
   echo $i
   case $i in
        4)
            echo "bad luck from China"
             ;; 
        9)
            echo "bad luck from Japan"
             ;;
         17)
            echo "bad luck from Italy"
             ;;
     esac
     i=$((i+1))
done
