#!/usr/bin/env bash
#Bash script that configures an ubuntu server.
#Backup the hosts file
cp /etc/hosts /etc/hosts.bak

#Add the custom entries to the hosts file
echo "127.0.0.2     localhost" > /etc/hosts.bak
echo "8.8.8.8       facebook.com" >> /etc/hosts.bak
cp -f /etc/hosts.bak /etc/hosts
