#!/usr/bin/env bash
# A Bash script to run Nginx as nginx on port 8080

# Update Nginx user in the configuration
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Change the listening port from 80 to 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Adjust permissions for the Nginx configuration file
chmod 644 /etc/nginx/nginx.conf

# Terminate any existing Apache2 processes
pkill apache2

# Start Nginx as the 'nginx' user
sudo -u nginx service nginx start
