#!/usr/bin/env bash
# A Bash script that uses ssh to connect to a server using,
# private key ~/.ssh/school

# Server address
server_address="35.153.66.82"
# Connect to the server
ssh -i ~/.ssh/school ubuntu@35.153.66.82
