#!/usr/bin/env bash
# A Bash script that creates an RSA key pair

# Specify the desired key name.
key_name="school"

# Specify the number of bits for the RSA key
key_bits=4096

# Specify the passphrase to protect the private key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b "$key_bits" -N "$passphrase" -f "$key_name"
